modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="firstmod"
version="${file.jarVersion}"
displayName="First Mod "
logoFile="examplemod.png"
credits="Rayunn1 mod's"
authors="Rayunn1"
description='''
My first mod
'''

[[dependencies.firstmod]] 
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firstmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"